framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\Messenger\Command\AddProductToCart': sync
            'App\Messenger\Command\RemoveProductFromCart': sync
            'App\Messenger\Command\AddProductToCatalog': sync
            'App\Messenger\Command\RemoveProductFromCatalog': sync
